[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pybromo"
version = "0.9.0"
description = "A simulator for single molecule FRET experiments of freely diffusing particles."
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name="Antonino Ingargiola", email="tritemio@gmail.com" },
]
license = { text = "GPL-2.0-only" }
classifiers=[
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering",
]
keywords = [
    "single-molecule FRET",
    "smFRET",
    "biophysics",
    "confocal",
    "freely-diffusing",
    "brownian-motion",
    "simulator",
]
dependencies = [
    "numpy",
    "scipy",
    "tables", # pytables
    "matplotlib>=3.1",
    "phconvert>=0.8",
    "jupyterlab",
    "numba",
]

[project.optional-dependencies]
gpu = ["cupy"]
dev = [
    "cython",
    "fretbursts @ git+https://github.com/OpenSMFS/FRETBursts.git",
]

[project.urls]
Homepage = "http://opensmfs.github.io/PyBroMo/"
Download = "https://github.com/OpenSMFS/PyBroMo"


[tool.setuptools.packages.find]
include = ["pybromo*"]

[tool.setuptools.package-data]
pybromo = ["psf_data/*"]

[tool.flake8]
max-line-length = 89
